### ISSUE TITLE
Update to Python3?

### ISSUE THREAD

**Issue by cdbavg400** [Clarivate-SAR/wos-amr#1]
Is there any chance you could update these files to python3? It is what I have installed on my computer here, and there are enough differences that I have not been able to make all of them myself without running into some errors. For instance, the urllib.Request changes have been most significant in python3.

**Comment by gneissone** [comment]
@cdbavg400 I have pushed a new branch that has been updated to use Python 3. https://github.com/Clarivate-SAR/wos-amr/tree/python3

Please give it a try and let me know if you have issues.

**Comment by cdbavg400** [comment]
@gneissone : 
Thank you for addressing this.

So I cannot figure out why, but when I run the lookup_ids.py script, the output.csv file is blank. The header row is there, but no data rows. I have checked the input file several times with numerous valid DOIs, and the output is still blank. For example:

Input: 
1)![image](https://user-images.githubusercontent.com/37788135/45440065-53f2dc80-b689-11e8-89d7-795f637694c7.png)

2)![image](https://user-images.githubusercontent.com/37788135/45441767-f90fb400-b68d-11e8-8642-e7037612e916.png)


Output (same in both cases): 
![image](https://user-images.githubusercontent.com/37788135/45439999-36257780-b689-11e8-9d7b-37837a9e0ce6.png)

EDIT: I just tested the issns_to_jcr.py script using the included example files, and I am getting the same problem there. An empty csv file with just the header row written.

**Comment by gneissone** [comment]
I tried with your 1st example and got a result. Are you sure the credentials are correct? The scripts will fail silently... paste `print(response.text)` after line 45 in client.py, rerun the script and let me know what response you see in your shell.

**Comment by cdbavg400** [comment]
You are correct. There is an issue with my access. I am getting the following xml:

```
<?xml version="1.0" encoding="UTF-8" ?>
<response xmlns="http://www.isinet.com/xrpc41" src="app.id=InternalVIVODemo">
<fn name="LinksAMR.retrieve" rc="Server.authentication">
<error code="Server.authentication">No matches returned for UserName "EPAwsp_HG"</error>
</fn>
</response>
```

Unless you can help with this issue, I will email my contacts at Clarivate and hopefully get a response soon. Thank you for your help.

**Comment by gneissone** [comment]
Please reach out to your Clarivate account manager or via the contact us form on clarivate.com for entitlements inquires.

**Comment by CamAnNguyen** [comment]
Sorry for bumping this up, I am having a problem with my credential as well. Is the `username` the email which I used to login into the Web of Science (https://webofknowledge.com)?

**Comment by gneissone** [comment]
@CamAnNguyen APIs require a separate username and password. Please reach out to your Clarivate account manager or via the contact form on clarivate.com if you do not already have API access.
