### ISSUE TITLE
Requests by Bibliographic Data

### ISSUE THREAD

**Issue by zuphilip** [Clarivate-SAR/wos-amr#2]
Currently, it is not possible to use this tools for all publications without a DOI or PMID. The WoS AMR allows to ask with any (?) combination of bibliographic data elements, e.g. Journal title + Volume + Issue - Start page. Any plans to support such requests here as well?

**Comment by gneissone** [comment]
It's actually already possible for any element except authors with lookup_ids.py, though undocumented. For example, take this input csv:
```
PMID,DOI,UT,atitle,stitle,year
,,,weighted median filters: A tutorial,IEEE TRANSACTIONS ON CIRCUITS AND SYSTEMS II-ANALOG AND DIGITAL SIGNAL PROCESSING,1996
,,000203011100014,,,
```
I believe you can use any combination of: Article title, journal title, ISSN, ISBN, volume, issue, year, starting page, author(s), UT, DOI, or PMID [[info](http://ipscience-help.thomsonreuters.com/LAMRService/WebServiceOperationsGroup/requestAPIWoS/descriptionXMLrequest/WoSMapSubsection3.html)]. I think the combination of elements must map to a single result or no results are returned.

**Comment by gneissone** [comment]
Addressed with https://github.com/Clarivate-SAR/wos-amr/commit/4c494267c44731a5e475a315193e4feae7ae5e87
