### ISSUE TITLE
Strange error message

### ISSUE THREAD

**Issue by ffigueras** [Clarivate-SAR/wos-amr#6]
After launching the script I got the following message, any clue ?

ERROR: The AMR API did not return any records. Response text:
<?xml version="1.0" encoding="UTF-8" ?>
<response xmlns="http://www.isinet.com/xrpc41" src="app.id=InternalVIVODemo">
<fn name="LinksAMR.retrieve" rc="Server.authentication">
<error code="Server.authentication">No Links AMR entitlement found for IP Address</error>
</fn>
</response>

**Comment by ffigueras** [comment]
On purpose I modified the Password and I still got the same message..

**Comment by gneissone** [comment]
The script is working on my end. Please note that credentials for the API are not the same as those for the Web of Science platform. For API credentials, please reach out to your account manager for the Web of Science. If you need help figuring out who that is, please email me at benjamin.gross@clarivate.com with your name, position, and institution.
